name = "Mlyn"
uuid = "fd5aada0-c151-4972-b421-44a88e14d743"
version = "0.1.0"
authors = ["Tikhon Belousov <2tishbel@gmail.com>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Distributions = "0.25.122"
JuliaFormatter = "2.1.6"
Random = "1.11.0"
